project:
  type: website
  output-dir: docs

website:
  title: "Hands-on protein modeling"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Introduction
      - href: homology.qmd
        text: Homology modeling
      - href: ai.qmd
        text: AI-based modeling
        



bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt



